branches:
  only:
    - master

matrix:
  include:
#    - os: linux
#      dist: xenial
#      sudo: required
#      env:
#        - ANSIBLE_FORCE_COLOR=1
    - os: osx
      osx_image: xcode10.1
      env:
        - ANSIBLE_FORCE_COLOR=1


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade ansible ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./ansible-setup-apt.sh ; fi
  # Remove MySQL.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y purge 'mysql*' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y autoremove ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y autoclean ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo rm -rf /var/lib/mysql ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo truncate -s 0 /var/log/mysql/error.log ; fi

script:
  - ansible-playbook -v dev-brew-provisioning.yml --syntax-check
  - ansible-playbook -v dev-brew-provisioning.yml
#  - >
#    ansible-playbook -v dev-brew-provisioning.yml | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  email: false
  slack: shanpu-hq:0eAmwVhkZYOehnlWhLtKQICP