---
- hosts: local
  connection: local
  strategy: linear
  roles:
    - name: common
      tags: common

    - name: font
      tags: font

    - name: dotfiles
      tags: dotfiles

    - name: fish
      tags: fish