---
- name: git clone my dotfiles
  git:
    repo: https://git@github.com/chez-shanpu/dotfiles
    dest: '{{ dotfiles_path }}'
    force: yes
  changed_when: false

- name: Put ".gitconfig" to home
  file:
    src: '{{ dotfiles_path }}/.gitconfig'
    dest: ~/.gitconfig
    state: link
    force: yes
  changed_when: false

- name: Put ".hyper.js"
  file:
    src: '{{ dotfiles_path }}/.hyper.js'
    dest: ~/.hyper.js
    state: link
    force: yes
  changed_when: false