---
- name: git clone my dotfiles
  git:
    repo: https://git@github.com/chez-shanpu/dotfiles
    dest: '{{ dotfiles_path }}'
    force: yes
    version: 'mac'
  changed_when: false

- name: Run provision.sh
  shell: '{{ dotfiles_path }}'/provision.sh