---
- hosts: all
  vars:
    github_user: chez-shanpu
    ghq_root: '~/ghq'
    repos_root: '{{ ghq_root }}/github.com/{{ github_user }}'
    dotfiles_path: '{{ repos_root }}/dotfiles'
  roles:
    - name: common
      tags: common