---
- block:
    - name: Apt update
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      become: yes
      apt:
        upgrade: safe

    - name: Install packages
      become: yes
      apt:
        name: '{{ packages }}'
        autoclean: yes
        autoremove: yes
      vars:
        packages:
          - build-essential
          - curl
          - git
          - m4
          - ruby
          - texinfo
          - libbz2-dev
          - libcurl4-openssl-dev
          - libexpat-dev
          - libncurses-dev
          - zlib1g-dev

  tags: linuxbrew_dependences_install

- name: Install linuxbrew
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  args:
    creates: ~/.linuxbrew/
  changed_when: false