name: ansible_test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  provisioning_test:
    runs-on: macos-latest
    env:
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: OverWrite brew link (to avoid error)
        run: brew link --overwrite python@3.9
      - name: Install Ansible
        run: brew install ansible
      - name: Install Ansible Lint
        run: brew install ansible-lint
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Syntax Check
        run: ansible-playbook -v ./dev-mac-provisioning.yml --syntax-check
      - name: Run Lint
        run: ansible-lint ./**/*.yml
      - name: Run Playbook
        run: ansible-playbook -v ./dev-mac-provisioning.yml
      - name: Idempotence Test
        run: |
          ansible-playbook -v ./dev-mac-provisioning.yml | grep -q 'changed=0.*failed=0' \
          && (echo 'Idempotence test: pass' && exit 0) \
          || (echo 'Idempotence test: fail' && exit 1)
