name: ansible_test
on:
  push:
    brances:
      - master
  pull_request:
    branches:
      - master
jobs:
  provisioning_test:
    runs-on: macos-latest
    env:
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - name: Install Ansible
        run: brew install ansible
      - name: Debug1
        run: pwd
      - name: Debug2
        run: ls ../ -a
      - name: Syntax Check
        run: ansible-playbook -v ./dev-brew-provisioning.yml --syntax-check
      - name: Runnning Playbook
        run: ansible-playbook -v ./dev-brew-provisioning.yml
